import http from "node:http";

const port = Number(process.env.DEMO_SERVER_PORT ?? 8787);
const apiBaseUrl = (process.env.DIGISIGN_API_BASE_URL ?? "https://sandbox.usedigisign.dev").replace(/\/$/, "");
const apiKey = process.env.DIGISIGN_API_KEY;
const configuredWorkspaceId = process.env.DIGISIGN_WORKSPACE_ID;

if (!apiKey) {
  console.error("Missing DIGISIGN_API_KEY. Copy .env.example to .env and set the server-side API key.");
  process.exit(1);
}

function responseValue(payload) {
  return payload?.data ?? payload?.value;
}

async function apiRequest(path, options = {}) {
  const response = await fetch(`${apiBaseUrl}${path}`, {
    ...options,
    headers: { Accept: "application/json", ...options.headers },
  });
  const payload = await response.json().catch(() => undefined);
  if (!response.ok) {
    throw new Error(payload?.meta?.message ?? `DigiSign API request failed (${response.status}).`);
  }
  return payload;
}

function createDemoPdf() {
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Length  ninety >>\nstream\nBT\n/F1 24 Tf\n72 700 Td\n(DigiSign React Native SDK Demo) Tj\n/F1 14 Tf\n0 -36 Td\n(This document was generated by the local demo server.) Tj\nET\nendstream",
  ];
  const stream = "BT\n/F1 24 Tf\n72 700 Td\n(DigiSign React Native SDK Demo) Tj\n/F1 14 Tf\n0 -36 Td\n(This document was generated by the local demo server.) Tj\nET\n";
  objects[4] = `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}endstream`;
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets[index + 1] = Buffer.byteLength(pdf);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(pdf, "ascii");
}

async function createSession() {
  const payload = await apiRequest("/v1/keys/session", {
    method: "POST",
    headers: { "x-api-key": apiKey },
  });
  const token = payload?.meta?.access_token;
  if (!token) throw new Error("DigiSign did not return meta.access_token from the session endpoint.");
  return token;
}

async function resolveWorkspace(sessionToken) {
  if (configuredWorkspaceId) return configuredWorkspaceId;
  const payload = await apiRequest("/v1/workspaces", {
    headers: { Authorization: `Bearer ${sessionToken}` },
  });
  const workspaces = responseValue(payload);
  const workspace = Array.isArray(workspaces) ? workspaces[0] : undefined;
  const workspaceId = workspace?.public_id ?? workspace?.id;
  if (!workspaceId) throw new Error("No workspace was returned. Set DIGISIGN_WORKSPACE_ID explicitly.");
  return workspaceId;
}

async function uploadDemoDocument(sessionToken, workspaceId) {
  const uploadSession = await apiRequest("/v1/media/single-use/upload-session", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${sessionToken}`,
      "x-ws-identifier": workspaceId,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      filename: "digisign-react-native-sdk-demo.pdf",
      mimetype: "application/pdf",
      purpose: "single_use_document",
    }),
  });
  const upload = responseValue(uploadSession);
  if (!upload?.upload_url || !upload?.upload_key) throw new Error("DigiSign returned an incomplete upload session.");
  const pdf = createDemoPdf();
  const uploadResponse = await fetch(upload.upload_url, {
    method: "PUT",
    headers: { "Content-Type": "application/pdf", "Content-Length": String(pdf.byteLength) },
    body: pdf,
  });
  if (!uploadResponse.ok) throw new Error(`Document upload failed (${uploadResponse.status}).`);
  return upload.upload_key;
}

async function createDemoRequest(sessionToken, workspaceId, uploadKey, recipient) {
  const payload = await apiRequest("/v1/requests/single-use", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${sessionToken}`,
      "x-ws-identifier": workspaceId,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      message: { subject: "DigiSign React Native SDK Demo" },
      expiration: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
      documents: [{ title: "DigiSign React Native SDK Demo", upload_key: uploadKey }],
      recipients: [recipient],
    }),
  });
  const request = responseValue(payload);
  const requestPublicId = request?.public_id;
  const recipientPublicId = request?.recipients?.[0]?.public_id;
  if (!requestPublicId || !recipientPublicId) throw new Error("DigiSign returned an incomplete signing request.");
  return { requestPublicId, recipientPublicId };
}

async function bootstrap(requestUrl) {
  const recipient = {
    name: requestUrl.searchParams.get("name") || process.env.DEMO_RECIPIENT_NAME || "DigiSign Demo Recipient",
    email: requestUrl.searchParams.get("email") || process.env.DEMO_RECIPIENT_EMAIL || "demo@example.com",
  };
  const sessionToken = await createSession();
  const workspaceId = await resolveWorkspace(sessionToken);
  const uploadKey = await uploadDemoDocument(sessionToken, workspaceId);
  const request = await createDemoRequest(sessionToken, workspaceId, uploadKey, recipient);
  return { ...request, accessToken: sessionToken, workspaceId, apiBaseUrl };
}

const server = http.createServer(async (request, response) => {
  response.setHeader("Access-Control-Allow-Origin", "*");
  response.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (request.method === "OPTIONS") {
    response.writeHead(204).end();
    return;
  }
  const requestUrl = new URL(request.url ?? "/", `http://${request.headers.host ?? `localhost:${port}`}`);
  if (request.method === "GET" && requestUrl.pathname === "/health") {
    response.writeHead(200, { "Content-Type": "application/json" }).end(JSON.stringify({ ok: true }));
    return;
  }
  if (request.method === "POST" && requestUrl.pathname === "/bootstrap") {
    try {
      const result = await bootstrap(requestUrl);
      response.writeHead(200, { "Content-Type": "application/json", "Cache-Control": "no-store" }).end(JSON.stringify(result));
    } catch (error) {
      console.error(error instanceof Error ? error.message : error);
      response.writeHead(502, { "Content-Type": "application/json" }).end(JSON.stringify({ error: "Unable to create the DigiSign demo request." }));
    }
    return;
  }
  response.writeHead(404).end();
});

server.listen(port, "0.0.0.0", () => {
  console.log(`DigiSign demo server listening on http://0.0.0.0:${port}`);
});
